Vagrant.configure("2") do |config|

  config.vagrant.plugins = ["vagrant-libvirt"]
  
  config.vm.provider :libvirt do |lb|
    lb.memory = 256
    lb.cpus = 1
  end

  config.vm.define "controller" do |node|
      node.vm.box = "generic/alma9"
      node.vm.network "private_network", ip: "192.168.33.100"
      node.vm.hostname = "controller"
  end
  N = 1
  (0..N).each do |id|
    config.vm.define "managed#{id}" do |node|
      node.vm.box = "generic/alma9"
      node.vm.network "private_network", ip: "192.168.33.#{10+id}"
      node.vm.hostname = "managed#{id}"
    end
  end
end