Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |lb|
    lb.memory = 1024
    lb.cpus = 2
  end
  config.vm.define "alma8" do |alma8|
     alma8.vm.box = "generic/alma8"
     alma8.vm.network = "private_network", ip: "192.168.33.11"
     alma8.vm.hostname = "alma8"
  end
  config.vm.define "stream" do |stream|
    stream.vm.box = "centos/stream8"
    stream.vm.network = "private_network", ip: "192.168.33.12"
    stream.vm.hostname = "stream"
  end
  config.vm.define "ubuntu" do |ubuntu|
    ubntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.network = "private_network", ip: "192.168.33.13"
    ubuntu.vm.hostname = "ubuntu"
  end
end