Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |lb|
    lb.memory = 1024
    lb.cpus = 2
  end
  config.vm.define "alma8" do |alma8|
     alma8.vm.box = "generic/alma8"
     alma8.vm.network "private_network", ip: "192.168.33.11"
     alma8.vm.hostname = "alma8"
  end
  config.vm.define "centos" do |centos|
    centos.vm.box = "generic/centos8s"
    centos.vm.network "private_network", ip: "192.168.33.12"
    centos.vm.hostname = "centos"
  end
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "generic/ubuntu1804"
    ubuntu.vm.network "private_network", ip: "192.168.33.13"
    ubuntu.vm.hostname = "ubuntu"
  end
end
